"""
changed is_staff, is_admin and is_superuser nullable=False

Revision ID: 18d4bdd7b983
Revises: b67cf71e5f4c
Create Date: 2026-08-12 13:41:03.177324
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18d4bdd7b983"
down_revision: str | Sequence[str] | None = "b67cf71e5f4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_staff", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_staff", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
