"""
add refresh tokens

Revision ID: abf0b5d773a7
Revises: 9540fc49a31f
Create Date: 2026-08-11 06:17:09.022955
"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "abf0b5d773a7"
down_revision: str | Sequence[str] | None = "9540fc49a31f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
