"""
added is_staff, is_admin and is_superuser to UserModel

Revision ID: b67cf71e5f4c
Revises: f621a65719ba
Create Date: 2026-08-12 13:36:18.245670
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b67cf71e5f4c"
down_revision: str | Sequence[str] | None = "f621a65719ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_staff", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "is_admin")
    op.drop_column("users", "is_staff")
    # ### end Alembic commands ###
