"""
add is_staff to users

Revision ID: b8886d6a36d6
Revises: 18d4bdd7b983
Create Date: 2026-08-16 13:09:04.157985
"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b8886d6a36d6"
down_revision: str | Sequence[str] | None = "18d4bdd7b983"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
