"""
add uuid default to users id

Revision ID: f621a65719ba
Revises: 2f2d9f1d1862
Create Date: 2026-08-12 11:01:34.079630
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f621a65719ba"
down_revision: str | Sequence[str] | None = "2f2d9f1d1862"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "id", existing_type=sa.UUID(), server_default=sa.text("gen_random_uuid()"), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    # ### end Alembic commands ###
